// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC14v8omXNSEOURbQRWSB1ppG802kAzbnQ',
    appId: '1:578505393903:web:9605cf523eb9e8383b3d1a',
    messagingSenderId: '578505393903',
    projectId: 'energy-re-imagined',
    authDomain: 'energy-re-imagined.firebaseapp.com',
    storageBucket: 'energy-re-imagined.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMegezdaVQpxGRKgDOJMpZe8Ja-caGdjU',
    appId: '1:578505393903:android:023cdda8958ef3be3b3d1a',
    messagingSenderId: '578505393903',
    projectId: 'energy-re-imagined',
    storageBucket: 'energy-re-imagined.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3KLRGQbTyGFS5Z_KPOC_D5wzgekAGI4',
    appId: '1:578505393903:ios:e62527dec6eb4d213b3d1a',
    messagingSenderId: '578505393903',
    projectId: 'energy-re-imagined',
    storageBucket: 'energy-re-imagined.appspot.com',
    iosBundleId: 'com.energy.re.imagined',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3KLRGQbTyGFS5Z_KPOC_D5wzgekAGI4',
    appId: '1:578505393903:ios:67e04ac4d10137433b3d1a',
    messagingSenderId: '578505393903',
    projectId: 'energy-re-imagined',
    storageBucket: 'energy-re-imagined.appspot.com',
    iosBundleId: 'com.energy.re.imagined.RunnerTests',
  );
}
